# This is going to be your local working both admin, api, etc.
version: "3.9"

# Networking
networks:
    test:
        driver: bridge 

services:    
    swoole:
        image: swoole:1.0
        build:
            context: ./ 
            dockerfile: Dockerfile
        container_name: swoole
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
          - "8080:8080"
        networks:
            - test
       